Adding "-strict" and "-2" parameters when using aac audio codec.
PHP-FFMpeg/PHP-FFMpeg pull request #519
Opened 2018-04-19 13:00 UTC by lucaasleaal

| Q                  | A
| ------------------ | ---
| Bug fix?           | yes
| New feature?       | no
| BC breaks?         | no
| Deprecations?      | no
| Fixed tickets      | fixes #issuenum
| Related issues/PRs | #issuenum
| License            | MIT

#### What's in this PR?

I changed the video class so when it get the command together, considering that if you're using aac audio codec, you are gonna need to use -strict -2 parameters before the last parameter (the output path).

#### Why?

When converting with libx264 and aac audio, the command outputs an error requesting the two added parameters by this PR.

#### To Do

- [ ] Create tests

2018-04-19 14:20 UTC, jens1o requested changes
Fix the codestyle and then add tests please. :)

2018-04-19 23:12 UTC, lucaasleaal commented
I don't really know how to add tests, what kind of documentation is required? Sorry I really don't know. If you could point me to the right direction I'd be glad to do the tests.

2018-04-20 16:15 UTC, jens1o commented
Okay, I just looked up and that would mean a huge effort, I'll do that for `v1.x`(the upcoming release branch).

2020-02-24 11:38 UTC, farazirfan47 commented
Can you please merge this PR ?

2026-03-03 12:39 UTC, closed without merging